export type OutputSize = { id: string; label: string; width: number; height: number };
export type OutputProfile = {
  id: string; name: string; description: string; sizes: OutputSize[];
  maxDuration: number; safeInset: number; audio: boolean; transparency: boolean;
  clickThrough: boolean; looping: boolean; exports: string[]; requirements: string[];
};

export const outputProfiles: OutputProfile[] = [
  { id: "display-advertising", name: "Display advertising", description: "Interactive, lightweight campaign banners.", sizes: [{ id: "300x250", label: "Medium rectangle", width: 300, height: 250 }, { id: "300x600", label: "Half page", width: 300, height: 600 }, { id: "728x90", label: "Leaderboard", width: 728, height: 90 }, { id: "970x250", label: "Billboard", width: 970, height: 250 }], maxDuration: 15, safeInset: 5, audio: false, transparency: false, clickThrough: true, looping: true, exports: ["HTML5 ZIP", "Fallback JPG"], requirements: ["Click-through URL", "Maximum three loops", "Lightweight assets"] },
  { id: "social-posts", name: "Social posts", description: "Short mobile-first posts, stories and reels.", sizes: [{ id: "1080x1920", label: "Story / Reel", width: 1080, height: 1920 }, { id: "1080x1350", label: "Portrait post", width: 1080, height: 1350 }, { id: "1080x1080", label: "Square post", width: 1080, height: 1080 }, { id: "1920x1080", label: "Landscape post", width: 1920, height: 1080 }], maxDuration: 60, safeInset: 10, audio: true, transparency: false, clickThrough: false, looping: false, exports: ["MP4", "PNG"], requirements: ["Keep important copy inside mobile safe zones", "Use captions when speech is present"] },
  { id: "digital-signage", name: "Digital signage", description: "Readable, long-running content for physical screens.", sizes: [{ id: "1920x1080", label: "Landscape screen", width: 1920, height: 1080 }, { id: "1080x1920", label: "Portrait screen", width: 1080, height: 1920 }, { id: "3840x2160", label: "4K landscape", width: 3840, height: 2160 }], maxDuration: 300, safeInset: 6, audio: false, transparency: false, clickThrough: false, looping: true, exports: ["MP4"], requirements: ["Large viewing-distance typography", "Seamless loop recommended"] },
  { id: "website-heroes", name: "Website heroes", description: "Responsive, lightweight website header motion.", sizes: [{ id: "1920x800", label: "Desktop wide", width: 1920, height: 800 }, { id: "1440x900", label: "Desktop standard", width: 1440, height: 900 }, { id: "750x1000", label: "Mobile hero", width: 750, height: 1000 }], maxDuration: 30, safeInset: 8, audio: false, transparency: true, clickThrough: true, looping: true, exports: ["WebM", "MP4", "Embed"], requirements: ["Silent autoplay", "Keep file weight low", "Responsive crop required"] },
  { id: "event-screens", name: "Event screens", description: "Announcements, countdowns and stage transitions.", sizes: [{ id: "1920x1080", label: "Full HD stage", width: 1920, height: 1080 }, { id: "3840x1080", label: "Ultra-wide stage", width: 3840, height: 1080 }, { id: "1080x1920", label: "Portrait kiosk", width: 1080, height: 1920 }], maxDuration: 180, safeInset: 8, audio: true, transparency: false, clickThrough: false, looping: true, exports: ["MP4", "PNG"], requirements: ["Large venue-safe text", "Avoid critical content near screen edges"] },
  { id: "livestream-graphics", name: "Livestream graphics", description: "Broadcast overlays, lower thirds and holding cards.", sizes: [{ id: "1920x1080", label: "Full HD broadcast", width: 1920, height: 1080 }, { id: "3840x2160", label: "4K broadcast", width: 3840, height: 2160 }], maxDuration: 60, safeInset: 10, audio: false, transparency: true, clickThrough: false, looping: true, exports: ["Transparent WebM", "PNG sequence"], requirements: ["Broadcast-safe margins", "Transparency supported"] },
  { id: "music-visualisers", name: "Music visualisers", description: "Audio-led lyrics, artwork and reactive motion.", sizes: [{ id: "1080x1920", label: "Vertical visualiser", width: 1080, height: 1920 }, { id: "1920x1080", label: "YouTube landscape", width: 1920, height: 1080 }, { id: "1080x1080", label: "Square visualiser", width: 1080, height: 1080 }], maxDuration: 900, safeInset: 8, audio: true, transparency: false, clickThrough: false, looping: false, exports: ["MP4"], requirements: ["Soundtrack required", "Lyric timing recommended", "Caption-safe text"] },
  { id: "presentations", name: "Presentations", description: "Title cards, section breaks and animated explainers.", sizes: [{ id: "1920x1080", label: "Widescreen 16:9", width: 1920, height: 1080 }, { id: "1600x1200", label: "Standard 4:3", width: 1600, height: 1200 }], maxDuration: 120, safeInset: 7, audio: true, transparency: false, clickThrough: false, looping: false, exports: ["MP4", "PNG"], requirements: ["Controlled playback", "Presentation-safe typography"] },
  { id: "email-messaging", name: "Email & messaging", description: "Compact motion and static campaign assets.", sizes: [{ id: "1200x628", label: "Message card", width: 1200, height: 628 }, { id: "600x600", label: "Email square", width: 600, height: 600 }, { id: "600x300", label: "Email banner", width: 600, height: 300 }], maxDuration: 8, safeInset: 7, audio: false, transparency: false, clickThrough: true, looping: true, exports: ["GIF", "PNG"], requirements: ["Small file size", "Readable without audio", "Static fallback"] },
  { id: "digital-invitations", name: "Digital invitations", description: "Shareable event invitations and save-the-dates.", sizes: [{ id: "1080x1920", label: "Story invitation", width: 1080, height: 1920 }, { id: "1080x1350", label: "Portrait invitation", width: 1080, height: 1350 }, { id: "1080x1080", label: "Square invitation", width: 1080, height: 1080 }], maxDuration: 45, safeInset: 9, audio: true, transparency: false, clickThrough: true, looping: false, exports: ["MP4", "PNG", "Web link"], requirements: ["Event date and location", "RSVP destination recommended"] },
  { id: "product-advertising", name: "Product advertising", description: "Offers, launches and product-led campaign creative.", sizes: [{ id: "1080x1920", label: "Vertical advert", width: 1080, height: 1920 }, { id: "1080x1080", label: "Square advert", width: 1080, height: 1080 }, { id: "1920x1080", label: "Landscape advert", width: 1920, height: 1080 }, { id: "970x250", label: "Display billboard", width: 970, height: 250 }], maxDuration: 30, safeInset: 8, audio: true, transparency: false, clickThrough: true, looping: false, exports: ["MP4", "HTML5 ZIP", "PNG"], requirements: ["Clear product hierarchy", "Offer and CTA recommended"] },
  { id: "fundraising-campaigns", name: "Fundraising campaigns", description: "Donation appeals, milestones and impact stories.", sizes: [{ id: "1080x1920", label: "Vertical appeal", width: 1080, height: 1920 }, { id: "1080x1080", label: "Square appeal", width: 1080, height: 1080 }, { id: "1920x1080", label: "Landscape appeal", width: 1920, height: 1080 }], maxDuration: 60, safeInset: 10, audio: true, transparency: false, clickThrough: true, looping: false, exports: ["MP4", "PNG", "Web link"], requirements: ["Donation destination", "Accessible contrast", "Impact statement recommended"] },
  { id: "educational-content", name: "Educational content", description: "Explainers, revision cards and learning sequences.", sizes: [{ id: "1920x1080", label: "Lesson landscape", width: 1920, height: 1080 }, { id: "1080x1920", label: "Mobile lesson", width: 1080, height: 1920 }, { id: "1080x1080", label: "Square learning card", width: 1080, height: 1080 }], maxDuration: 300, safeInset: 9, audio: true, transparency: false, clickThrough: false, looping: false, exports: ["MP4", "PNG"], requirements: ["Readable pacing", "Captions for narration", "Clear learning sequence"] },
  { id: "creator-templates", name: "Creator templates", description: "Flexible reusable compositions for future projects.", sizes: [{ id: "1080x1920", label: "Vertical", width: 1080, height: 1920 }, { id: "1080x1080", label: "Square", width: 1080, height: 1080 }, { id: "1920x1080", label: "Landscape", width: 1920, height: 1080 }], maxDuration: 120, safeInset: 8, audio: true, transparency: true, clickThrough: true, looping: true, exports: ["MP4", "WebM", "PNG", "Template package"], requirements: ["Reusable placeholder copy", "Flexible media slots"] },
];

export const profileById = (id?: string) => outputProfiles.find((profile) => profile.id === id) || outputProfiles.find((profile) => profile.id === "social-posts")!;
export const profileByName = (name?: string) => outputProfiles.find((profile) => profile.name === name) || profileById();
