"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function AdminSetupPage() {
  const router = useRouter(); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [setupKey, setSetupKey] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (password !== confirm) { setMessage("Passwords do not match."); return; } setBusy(true); setMessage(""); const response = await fetch("/api/admin/setup", { method: "POST", headers: { "content-type": "application/json", ...(setupKey ? { "x-motionmint-setup-key": setupKey } : {}) }, body: JSON.stringify({ username, password }) }); const result = await response.json() as { error?: string }; setBusy(false); if (!response.ok) { setMessage(result.error || "Could not create administrator."); return; } router.push("/admin/login"); };
  return <main className="admin-auth-page"><section className="admin-auth-card"><span className="brand">Turnbine</span><p className="auth-eyebrow">First-time setup</p><h1>Create administrator</h1><p>This closes permanently after the first admin account is created.</p><form onSubmit={submit}><label>Production setup key<input type="password" autoComplete="off" value={setupKey} onChange={(event) => setSetupKey(event.target.value)} /><small>Required on the production site only.</small></label><label>Admin username<input required minLength={4} autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} /></label><label>Password<input required minLength={12} type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>Confirm password<input required minLength={12} type="password" autoComplete="new-password" value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label>{message && <p className="auth-error" role="alert">{message}</p>}<button className="auth-submit" disabled={busy}>{busy ? "Creating…" : "Create admin →"}</button></form><div className="admin-auth-links"><Link href="/admin/login">Back to admin login</Link></div></section></main>;
}
